name: CI

on:
  pull_request:
    branches:
      - main  # You can change this to match the default branch (e.g., master)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Upload test results (optional)
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results/
